Frequency of unique characters of a String
Developer-Students-Club-MAIT/cool_code_snippets pull request #10
Opened 2020-10-04 19:15 UTC by YashSaxena9

# Frequency of characters

The following snippet finds the frequency of all unique readable characters present in a string and writes the frequency count in an output file.

Fixes #4 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generates no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2020-10-05 06:01 UTC, kaustubhgupta approved these changes

2020-10-05 22:45 UTC, sakshamarora1 requested changes
Thank you for opening a Pull Request :partying_face:!
This looks great! Just a single change :)

2020-10-05 22:45 UTC, sakshamarora1 commented on snippets/java/charFreqCount.md
> +                res.append("character '" + (char)(' ' + i) + "' present :" + chars[i] + " times\n");
I think a proper sentence will look better along with the corresponding changes in the output block. :)
```suggestion
                res.append("The character '" + (char)(' ' + i) + "' occurred " + chars[i] + " times.\n");
```

2020-10-06 15:10 UTC, YashSaxena9 commented
Changes are done, please have a look. :)

2020-10-06 17:23 UTC, sakshamarora1 commented
The output block isn't updated yet. @YashSaxena9
Looks good and will be ready to merge after this. :D

2020-10-06 18:16 UTC, YashSaxena9 commented
Updated the output block, hope this resolves all problems now. :)

2020-10-06 18:58 UTC, sakshamarora1 approved these changes

2020-10-06 18:58 UTC, merged

2020-10-06 19:02 UTC, YashSaxena9 commented
I'm sorry but their's no tag regarding `Hacktoberfest-accepted` which is compulsory for a PR to count for Hacktoberfest submission.
Is this repository not counted for Hacktoberfest?

2020-10-07 00:14 UTC, sakshamarora1 commented
@YashSaxena9 I have added the appropriate label! Thanks for noticing.