Emerging Rainbow
Developer-Students-Club-MAIT/cool_code_snippets pull request #12
Opened 2020-10-10 02:47 UTC by einhawking

# Emerging Rainbow in C++

This code is about making a rainbow emerge from time=0 seconds. This code helps to gain a deeper understanding of using graphics in C++.

## Type of change

-  New feature (non-breaking change which adds functionality)

# Checklist:

-  My code follows the style guidelines of this project
-  I have performed a self-review of my own code
-  I have commented my code, particularly in hard-to-understand areas
-  I have made corresponding changes to the documentation
-  My changes generates no new warnings
-  I have added tests that prove my fix is effective or that my feature works
-  New and existing unit tests pass locally with my changes
-  Any dependent changes have been merged and published in downstream modules

2020-10-10 07:51 UTC, kaustubhgupta requested changes

2020-10-10 07:51 UTC, kaustubhgupta commented on snippets/c++/Emerging_Rainbow.md
> +
Remove these trailing spaces

2020-10-10 07:51 UTC, kaustubhgupta commented on snippets/c++/Emerging_Rainbow.md
> +https://drive.google.com/file/d/1BMZbuWzrROUu0wjm0eleGJzrJbUcl7fH/view?usp=sharing
Insert the output image here only

2020-10-10 07:51 UTC, kaustubhgupta commented on snippets/c++/Emerging_Rainbow.md
> +| --- | --- | --- |
Correct the spelling of our college

2020-10-10 10:27 UTC, einhawking commented
I've made the required changes, please check.

2020-10-11 13:10 UTC, kaustubhgupta approved these changes

2020-10-12 06:57 UTC, sakshamarora1 requested changes
@einhawking This looks great! Thanks for this contribution. Just a few changes and it'll be ready to merge!

2020-10-12 06:57 UTC, sakshamarora1 commented on snippets/c++/Emerging_Rainbow/Emerging_Rainbow.md
> +#### Langauge
We should keep the heading size fixed to h2 (i.e. ##) just like in other files.

2020-10-12 06:57 UTC, sakshamarora1 commented on snippets/c++/Emerging_Rainbow/Emerging_Rainbow.md
> +Feature
We don't need to add a type of issue heading here.
```suggestion
```

2020-10-12 06:57 UTC, sakshamarora1 commented on snippets/c++/Emerging_Rainbow/Emerging_Rainbow.md
> +This code is about making a rainbow emerge from time=0 seconds.
Adding this under a description sub heading will be better.

2020-10-12 06:57 UTC, sakshamarora1 commented on snippets/c++/Emerging_Rainbow/Emerging_Rainbow.md
> +![Rainbow Image](https://github.com/einhawking/cool_code_snippets/blob/master/snippets/c%2B%2B/Emerging_Rainbow/Rainbow_image.PNG)
If possible can you add a gif of the output, it'll look very cool. :D

2020-10-13 04:07 UTC, einhawking commented
I've left the speed of gif as the original speed. Hope it's okay.

2020-10-13 07:35 UTC, merged