Added Dictionary using Trie Python code
Developer-Students-Club-MAIT/cool_code_snippets pull request #34
Opened 2020-10-18 22:07 UTC by arnab031

# Added Dictionary using Trie Python code

Related: #24

## Type of change

- [Y] New feature (non-breaking change which adds functionality)

# Checklist:

- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [Y] I have commented my code, particularly in hard-to-understand areas
- [Y] I have made corresponding changes to the documentation
- [Y] My changes generates no new warnings
- [Y] I have added tests that prove my fix is effective or that my feature works
- [Y] New and existing unit tests pass locally with my changes
- [Y] Any dependent changes have been merged and published in downstream modules

2020-10-19 06:34 UTC, deepika-rana requested changes
All requirements completed except including the prebuilt words mentioned.

2020-10-19 11:36 UTC, arnab031 commented
I have added prebuilt words mentioned. Please check it.

2020-10-19 12:27 UTC, deepika-rana approved these changes

2020-10-20 22:18 UTC, sakshamarora1 requested changes
Looks good! Just a few changes.

2020-10-20 22:18 UTC, sakshamarora1 commented on snippets/python/dictionary_using_trie_python.md
> +letter and the letter within the node's branch matches. You can learn more about inserting and searching, and tries in general [here](https://www.geeksforgeeks.org/trie-insert-and-search/)
Add this stuff under the Description sub-heading like this:

## Description
### Trie
Trie is an efficient data retrieval structure which builds upon the properties of tree structure. Word search complexitites
can be brought to an optimal limit which depends on key length.

### Traversing the trie
Main application of the trie is storing words in the structure. This trie can be traversed by first approaching the root node then traversing along the path on which our 
letter and the letter within the node's branch matches. You can learn more about inserting and searching, and tries in general [here](https://www.geeksforgeeks.org/trie-insert-and-search/)

2020-10-20 22:18 UTC, sakshamarora1 commented on snippets/python/dictionary_using_trie_python.md
> +## Python Code
```suggestion
## Code
```

2020-10-20 22:18 UTC, sakshamarora1 commented on snippets/python/dictionary_using_trie_python.md
> +TrieNode definition, Recursive functions for searching, inserting and a few helper functions are given in the following code snippet.
Move this to under the `Description` block

2020-10-21 17:27 UTC, kaustubhgupta approved these changes

2020-10-22 13:10 UTC, sakshamarora1 approved these changes

2020-10-22 13:11 UTC, merged