Add Tic-Tac-Toe Game code in python
Developer-Students-Club-MAIT/cool_code_snippets pull request #38
Opened 2020-10-19 17:33 UTC by arnab031

# Add Tic-Tac-Toe Game code in python

Related: #14 

## Type of change

- [Y] New feature (non-breaking change which adds functionality)

# Checklist:

- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [Y] I have commented my code, particularly in hard-to-understand areas
- [Y] I have made corresponding changes to the documentation
- [Y] My changes generates no new warnings
- [Y] I have added tests that prove my fix is effective or that my feature works
- [Y] New and existing unit tests pass locally with my changes
- [Y] Any dependent changes have been merged and published in downstream modules

2020-10-20 22:03 UTC, sakshamarora1 requested changes
Good work! I have left some comments for changes, go through them :D

2020-10-20 22:03 UTC, sakshamarora1 commented on snippets/python/tic_tac_toe_game_using_python.md
> +# Tic-Tac-Toe game for multiplayer
```suggestion
# Tic-Tac-Toe
```

2020-10-20 22:03 UTC, sakshamarora1 commented on snippets/python/tic_tac_toe_game_using_python.md
> +Tic-Tac-Toe is a multiplayer simple game.
This is redundant. If you want to add stuff about the working of the code you can do so under the `Description` sub-heading

2020-10-20 22:03 UTC, sakshamarora1 commented on snippets/python/tic_tac_toe_game_using_python.md
> +
```suggestion
```

2020-10-20 22:03 UTC, sakshamarora1 commented on snippets/python/tic_tac_toe_game_using_python.md
> +
```suggestion
```

2020-10-20 22:03 UTC, sakshamarora1 commented on snippets/python/tic_tac_toe_game_using_python.md
> +
```suggestion
```

2020-10-20 22:03 UTC, sakshamarora1 commented on snippets/python/tic_tac_toe_game_using_python.md
> +        # for mac and linux(here, os.name is 'posix')
```suggestion
    # for mac and linux(here, os.name is 'posix')
```

2020-10-20 22:03 UTC, sakshamarora1 commented on snippets/python/tic_tac_toe_game_using_python.md
> +str1 = "."
Can you come up with a better informative naming for these variables. For example, `box1`, `block1`, etc.
This goes for all the other variables too. To make it easier for other people to comprehend what's happening without wasting too much time!

2020-10-21 17:30 UTC, kaustubhgupta approved these changes
LGTM :-)

2020-10-22 13:09 UTC, sakshamarora1 approved these changes

2020-10-22 13:09 UTC, merged