Caesar added
Developer-Students-Club-MAIT/cool_code_snippets pull request #46
Opened 2020-10-24 07:27 UTC by ShivamPorwal02

# Added Caesar

Fixes: #17 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generates no new warnings

2020-10-25 04:22 UTC, kaustubhgupta approved these changes

2020-10-25 11:16 UTC, sakshamarora1 requested changes
Looks great! Just a few changes.

2020-10-25 11:16 UTC, sakshamarora1 commented on snippets/c++/caesar.md
> +## Demo
I think this will look better. :)
```suggestion
## Example
For this example, key = -8
```

2020-10-25 11:16 UTC, sakshamarora1 commented on snippets/c++/caesar.md
> +    //Rejects if user don't provide key
```suggestion
    //Rejects if user doesn't provide a key
```

2020-10-28 03:39 UTC, kaustubhgupta commented
@ShivamPorwal02 are you working on this?

2020-10-30 05:14 UTC, closed without merging