Added tic-tac-toe-C++.md
Developer-Students-Club-MAIT/cool_code_snippets pull request #54
Opened 2020-12-25 10:49 UTC by Rayman-Sodhi

# Title/Heading
Added Tic-tac-toe-C++.md

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generates no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-30 11:34 UTC, kaustubhgupta requested changes

2020-12-30 11:34 UTC, kaustubhgupta commented on challenges/tic-tac-toe-C++.md
> +# Rules of the Game
Maintain the level of headings. As the first one level one, so other levels should be level 2 (##)

2020-12-30 16:45 UTC, Rayman-Sodhi commented
Made changes in the level of the font.

2020-12-31 09:38 UTC, kaustubhgupta approved these changes

2020-12-31 16:22 UTC, merged