Code snippet for Longest Common Subsequence
Developer-Students-Club-MAIT/cool_code_snippets pull request #9
Opened 2020-10-04 14:23 UTC by ShivamPorwal02

# Title/Heading

Code snippet for Longest Common Subsequence

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generates no new warnings

2020-10-04 18:53 UTC, sakshamarora1 requested changes
Thank you for opening a Pull Request @ShivamPorwal02 :D
Just a few things

2020-10-04 18:54 UTC, sakshamarora1 requested changes
Thank you for opening a Pull Request @ShivamPorwal02 :D
Just a few things
Also please edit the PR description accordingly. Thanks

2020-10-04 18:54 UTC, sakshamarora1 commented on snippets/python/Longest_common_subsequence.md
> +# Input strings
We should only keep important comments. Please see to that. :)

2020-10-04 18:54 UTC, sakshamarora1 commented on snippets/python/Longest_common_subsequence.md
> +| Shivam Porwal | ShivamPorwal02 | Maharaja Surajmal Intitute of Technology |
```suggestion
| Shivam Porwal | ShivamPorwal02 | Maharaja Surajmal Institute of Technology |
```

2020-10-05 05:59 UTC, kaustubhgupta requested changes

2020-10-05 05:59 UTC, kaustubhgupta commented on snippets/python/Longest_common_subsequence.md
> +# Least Common Subsequence
*longest

2020-10-05 09:47 UTC, ShivamPorwal02 commented
@kaustubhgupta @sakshamarora1 I have made the requested changes, please review.

2020-10-05 17:00 UTC, kaustubhgupta approved these changes

2020-10-05 22:34 UTC, sakshamarora1 approved these changes

2020-10-05 22:36 UTC, merged